apiVersion: v1
kind: Service
metadata:
  name: bonsai-frontend
  namespace: bonsai
  labels:
    app: bonsai-frontend
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: bonsai-frontend
    tier: frontend