name: Kubernetes Deployment

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-to-eks:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name bonsai-cluster --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infra/k8s/eks/deployments/
          kubectl apply -f infra/k8s/eks/services/
          kubectl apply -f infra/k8s/eks/networkpolicies/
          kubectl apply -f infra/k8s/eks/storage/
          kubectl apply -f infra/k8s/eks/autoscaling/  
          kubectl apply -f infra/k8s/eks/ingress.yaml
